# Generated by Django 4.2.5 on 2023-10-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
