# Generated by Django 4.2.5 on 2023-11-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlist',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
