# Generated by Django 4.2.5 on 2023-11-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatlist_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlist',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
