# Generated by Django 4.2.5 on 2023-09-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='propertyImage'),
        ),
    ]
