# Generated by Django 4.2.5 on 2023-09-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='propertyImage'),
        ),
    ]
