# Generated by Django 4.2.5 on 2023-10-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='property',
            name='logitude',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
