# Generated by Django 4.2.5 on 2023-10-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_latitude_property_logitude_property_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='logitude',
            new_name='longitude',
        ),
    ]
