# Generated by Django 4.2.5 on 2023-10-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_rename_logitude_property_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='is_rent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_sell',
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('rent', 'rent'), ('sale', 'sale')], default=None, max_length=30),
        ),
    ]
