# Generated by Django 4.2.5 on 2023-11-02 09:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0011_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Comments',
        ),
    ]
