# Generated by Django 4.2.5 on 2023-09-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.BigIntegerField(null=True),
        ),
    ]
