# Generated by Django 4.2.5 on 2023-09-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('otp', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
