# Generated by Django 4.2.5 on 2023-09-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_ending',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_starting',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
